config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'films#index'

  resources :actors, only: %i[index show new create destroy]
  resources :films, only: %i[index show new create destroy] do
    scope module: :films do
      resources :reviews, only: %i[create]

    end
  end

  get '/films/:id'=>'films#show'
  get 'popularfilm' => 'popularfims#popularfilm'
  resources :reviews, only: :destroy
end

app/controllers/popularfims_controller.rb
class PopularfimsController < ApplicationController
  before_action :authenticate_user!

  def popularfilm
    @pagy, @films = pagy(Film.includes(:reviews).joins(:reviews).order("count DESC"))
  end
end

app/helpers/popularfims_helper.rb
module PopularfimsHelper
end

app/views/popularfims/_list_item.html.erb
<article class="media container">

  <figure class="media-left film-photo">
    <p class="image is-128x128">
      <%= image_tag item.photo.blank? ? 'https://bulma.io/images/placeholders/128x128.png' : url_for(item.photo) %>
    </p>
  </figure>

  <div class="media-content">
    <div class="content">
      <p>
        <%=link_to item.name, film_path(item), "data-turbolinks": false%>
        <br>
        <%= item.description %>
      </p>
    </div>

    <div>
      <%=item.count%>
      <i class="fa fa-eye"></i>
    </div>
  </div>
  <div class="media-right">
    <%= button_tag '', class: 'delete', data: { 'js-film-delete': true,
                                                turbolinks: false,
                                                confirm: t('.delete_confirm'),
                                                url: film_path(item) } %>
  </div>
</article>

app/views/popularfims/popularfilm.erb
<%= content_for :content_title do %>
  <span class="icon-text">
        <span class="icon">
          <i class="fa fa-fire" aria-hidden="true"></i>
        </span>
        <span><%= 'Most discussed films' %></span>
      </span>
<% end %>
<% if user_signed_in? %>
  <span class="auto">
  <span>Welcome, <%= current_user.email %></span>

    <span class="button"> <%= link_to 'Exit', destroy_user_session_path, :method => :delete %>
      <style>.button {
          margin-bottom: 20px
      }</style></span>

<% else %>
  <%= link_to 'Sign in', new_user_session_path %> или <%= link_to 'Creane new account', new_user_registration_path %>
<% end %>
<div class="films" data-js-films>

  <% if @films.any? %>

    <% @films.includes(:reviews).each do |film| %>

      <%= render 'list_item', item: film %>
    <% end %>
    <%== pagy_bulma_nav(@pagy) %>
  <% else %>
    <p class="has-text-centered is-size-6"><%= t('.no_items') %></p>
  <% end %>
</div>
</span>