config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'films#index'

  resources :actors, only: %i[index show new create destroy]
  resources :films, only: %i[index show new create destroy] do
    scope module: :films do
      resources :reviews, only: %i[create]

    end
  end

  get '/films/:id'=>'films#show'
  get 'popularfilm' => 'popularfims#popularfilm'
  resources :reviews, only: :destroy
end

app/models/film.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: films
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null

class Film < ApplicationRecord
  MIN_DESCRIPTION_LENGTH = 10
  MAX_DESCRIPTION_LENGTH = 250

  has_many :actor_films
  has_many :actors, through: :actor_films
  has_many :reviews, dependent: :delete_all

  has_one_attached :photo

  validates :name, :description, presence: true
  validates :description,
            length: { minimum: MIN_DESCRIPTION_LENGTH, maximum: MAX_DESCRIPTION_LENGTH }
end

app/controllers/films/reviews_controller.rb
# frozen_string_literal: true

module Films
  class ReviewsController < ApplicationController
    def create
      @film   = Film.find(params[:film_id])
      @review = Review.create(film: @film, **comment_params)

      return create_failure if @review.errors.any?

      redirect_to film_path(@film, anchor: 'new-review'),
                  notice: I18n.t('films.reviews.create.success')
    end

    private

    def comment_params
      params.require(:review).permit(:text, :username)
    end

    def create_failure
      redirect_to film_path(@film, anchor: 'new-review'),
                  alert: @review.errors.full_messages.first
    end
  end
end

app/controllers/films_controller.rb
# frozen_string_literal: true

class FilmsController < ApplicationController
  before_action :find_film!, only: %i[show destroy]
  before_action :authenticate_user!

  def index
    @films         = Film.all
    @pages, @films = pagy(Film.includes(:photo_blob).order(created_at: :desc))
  end

  def show
    @films      = Film.all
    @film.increment!(:count)
    @review     = Review.new
    @film_actor = @film.actor_films.build
  end

  def new
    @actors2    = Actor.all
    @film       = Film.new
    @all_films  = Film.all
    @film_actor = @film.actor_films.build
  end

  def create
    @film = Film.create(film_params)
    params[:actors][:id].each do |film|
      @film.actor_films.build(actor_id: film) unless film.empty?
    end

    params[:actors][:id].each do |actor_id2|
      if actor_id2.to_i > 0
        ActorFilm.create(actor_id: actor_id2.to_i, film_id: @film.id)
      end
    end

    return render :new if @film.errors.any?

    redirect_to films_path, notice: I18n.t('films.create.success')
  end

  # JSON response example
  def destroy
    @film.destroy!

    respond_to do |format|
      format.html { redirect_to films_path, notice: I18n.t('films.destroy.message') }
      format.json do
        render json: { data: { message: I18n.t('films.destroy.json_message', name: @film.name) } }
      end
    end
  end

  private

  def find_film!
    @film = Film.find(params[:id])
  end

  def film_params
    params.require(:film).permit(:name, :description)
  end

  def actorfilm_params
    params.require(:actors).permit(:id, :film_id)
  end

end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  def destroy
    review = Review.find(params[:id])
    review.destroy

    redirect_to film_path(review.film, anchor: 'new-review'),
                notice: I18n.t('reviews.destroy.message')
  end
end

app/views/films/reviews/_form.html.erb
<%= form_for [film, review], html: { id: 'new-review' } do |f| %>
  <article class="media mb-5">
    <div class="media-content">
      <div class="field">
        <p class="control">
          <%= f.text_area :text, class: 'textarea', placeholder: t('.text_placeholder') %>
          <br>
          <%= f.text_area :username, placeholder: ('Enter a username...') %>
        </p>
      </div>
      <%= f.submit t('generic.submit'), class: 'button is-info is-pulled-right' %>
    </div>
  </article>
<% end %>

app/views/films/reviews/_list.html.erb
<% if reviews.any? %>

  <% reviews.each do |review| %>
    <%= render 'films/reviews/list_item', model: review %>
  <% end %>

<% else %>
  <p class="has-text-centered is-size-6"><%= t('.no_items') %></p>
<% end %>

app/views/films/reviews/_list_item.html.erb
<article class="media">
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= model.username %></strong>
        <br>
        <%= model.text %>


      </p>
    </div>
  </div>

  <div class="media-right">
    <%= link_to '', review_path(model), method: :delete,
                class: 'delete',
                data: { confirm: t('.delete_confirm') } %>
  </div>
</article>

app/views/films/reviews/most.index.html.erb
<%= content_for :content_title do %>
  <span class="icon-text">
    <span class="icon">
      <i class="fas fa-film"></i>
    </span>
    <span><%= t('films.nav') %></span>
  </span>
<% end %>
<% content_for :content_title_actions do %>
  <%  link_to mosts_path do %>
    <span class="icon-text">
      <span class="icon">
        <i class="fas fa-plus-circle"></i>
      </span>
      <span><%= t('generic.add_new') %></span>
    </span>
  <% end %>
<% end %>

<div class="films" data-js-films>
  <% if @films.any? %>

    <% @films.each do |film| %>
      <%= render 'list_item', item: film %>
    <% end %>
    <%== pagy_bulma_nav(@pages) %>
  <% else %>
    <p class="has-text-centered is-size-6"><%= t('.no_items') %></p>
  <% end %>
</div>