config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'films#index'

  resources :actors, only: %i[index show new create destroy]
  resources :films, only: %i[index show new create destroy] do
    scope module: :films do
      resources :reviews, only: %i[create]

    end
  end

  get '/films/:id'=>'films#show'
  get 'popularfilm' => 'popularfims#popularfilm'
  resources :reviews, only: :destroy
end

app/models/actor.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: actors
#
#  id               :bigint           not null, primary key
#  description      :text
#  full_name        :string
#  gender           :string
#  is_married       :boolean          default(FALSE)
#  number_of_oscars :integer          default(0)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Actor < ApplicationRecord
  MIN_FULL_NAME_LENGTH = 3
  MAX_FULL_NAME_LENGTH = 25
  MIN_DESC_LENGTH      = 10
  MAX_DESC_LENGTH      = 250

  has_many :actor_films
  has_many :films, through: :actor_films

  has_one_attached :image

  validates :full_name, :description, :gender, presence: true

  validates :full_name,
            length: { minimum: MIN_FULL_NAME_LENGTH, maximum: MAX_FULL_NAME_LENGTH }
  validates :description,
            length: { minimum: MIN_DESC_LENGTH, maximum: MAX_DESC_LENGTH }

  enum gender: {
    male:   MALE   = 'male',
    female: FEMALE = 'female',
    other:  OTHER  = 'other'
  }
end

app/controllers/actors_controller.rb
# frozen_string_literal: true

class ActorsController < ApplicationController
  before_action :find_actor!, only: %i[show destroy]
  before_action :authenticate_user!

  def index
    @pagy, @actors = pagy(Actor.order(created_at: :desc))
    @actors        = Actor.all
  end

  def new
    @actor  = Actor.new
    @actors = Actor.all
  end

  def create
    @actor = Actor.create(actor_params)

    return render :new if @actor.errors.any?

    redirect_to actors_path, notice: I18n.t('actors.create.success')
  end

  def destroy
    @actor.destroy!

    redirect_to actors_path, notice: I18n.t('actors.destroy.message', name: @actor.full_name)
  end

  private

  def find_actor!
    @actor = Actor.find(params[:id])
  end

  def actor_params
    params.require(:actor).permit(:full_name, :description, :number_of_oscars, :gender, :is_married)
  end
end

app/views/actors/_list_item.html.erb
<article class="media container">
  <figure class="media-left actor-photo">
    <p class="image is-128x128">
      <%= image_tag item.image.blank? ? 'https://bulma.io/images/placeholders/128x128.png' : url_for(item.image)%>
    </p>
  </figure>

  <div class="media-content">
    <p>
      <%=link_to item.full_name, item%>
      <br>
      <%= item.description %>
    </p>
  </div>

  <div class="media-right">
    <%= link_to '', actor_path(item), method: :delete,
                class: 'delete',
                data: { confirm: t('.delete_confirm') } %>
  </div>
</article>

app/views/actors/index.html.erb
<%= content_for :content_title do %>
  <span class="icon-text">
        <span class="icon">
       <i class="fa fa-users" aria-hidden="true"></i>
        </span>
        <span><%= 'Actors' %></span>
      </span>
<% end %>

<% content_for :content_title_actions do %>
  <%= link_to new_actor_path do %>
    <span class="icon-text">
      <span class="icon">
        <i class="fas fa-plus-circle"></i>
      </span>
      <span><%= t('generic.add_new') %></span>
    </span>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <span class="auto">
  <span>Welcome, <%= current_user.email %></span>
    <span class="button"> <%= link_to 'Exit' , destroy_user_session_path, :method => :delete %><style>
          .button{margin-bottom: 20px}
      </style>
    </span>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %> или <%= link_to 'Creane new account', new_user_registration_path %>
  </span>
<% end %>

<div class="actors" data-js-actors>
  <% if @actors.any? %>

    <% @actors.each do |film| %>
      <%= render 'list_item', item: film %>
    <% end %>

    <%== pagy_bulma_nav(@pagy) %>

  <% else %>
    <p class="has-text-centered is-size-6"><%= t('.no_items') %></p>
  <% end %>
</div>

app/views/actors/new.html.erb
<% content_for :content_title_class %>
<% content_for :content_title_actions do %>
  <%= link_to actors_path do %>
    <span class="icon-text">
      <span class="icon">
        <i class="fas fa-arrow-left"></i>
      </span>
      <span><%= t('generic.back') %></span>
    </span>
  <% end %>
<% end %>

<%= content_for :content_title do %>
  <span class="icon-text">
    <span class="icon">
      <i class="fas fa-plus"></i>
    </span>
    <span><%= t('.title') %></span>
  </span>
<% end %>

<%= simple_form_for @actor do |f| %>
  <div class="content p-5 px-6">
    <div class="columns">
      <div class="column is-two-fifths">
        <%= f.input :full_name, required: false %>
        <%= f.input :description, as: :text %>
      </div>

      <div class="column">
        <%= f.input :number_of_oscars, as: :integer, input_html: { value: nil } %>
        <%= f.input :gender, collection: enum_collection_for_select(Actor, :gender, placeholder: true),
                             prompt: false %>
        <%= f.input :is_married, as: :boolean %>
      </div>
    </div>
  </div>

  <div class="content-footer has-text-right">
    <%= f.button :submit, value: t('generic.save') %>
  </div>
<% end %>

app/views/actors/show.html.erb
<% content_for :content_title_class, 'is-danger' %>
<%= content_for :content_title do %>
  <span class="icon-text">
    <span class="icon">
      <i class="fas fa-user"></i>
    </span>
    <span><%= @actor.full_name %></span>
  </span>
<% end %>

<% content_for :content_title_actions do %>
  <%= link_to actors_path do %>
    <span class="icon-text">
      <span class="icon">
        <i class="fas fa-arrow-left"></i>
      </span>
      <span><%= t('generic.back') %></span>
    </span>
  <% end %>
<% end %>

<div class="content p-5 px-6">
  <div class="columns">
    <div class="column is-two-fifths">
      <figure class="image film-photo m-0">
        <%= image_tag @actor.image.blank? ? 'https://bulma.io/images/placeholders/128x128.png' : url_for(@actor.image) %>
      </figure>
    </div>
    <div class="column">
      <div class="columns">
        <div class="group column is-half mb-5">
          <label class="has-text-weight-bold mr-3">
            <%= Actor.human_attribute_name(:gender) %>
            :
          </label>
          <p class="has-text-justified is-inline"><%= @actor.gender %></p>
        </div>

        <div class="group column is-half mb-5">
          <label class="has-text-weight-bold mr-3">
            <%= Actor.human_attribute_name(:number_of_oscars) %>
            :
          </label>
          <p class="has-text-justified is-inline"><%= @actor.number_of_oscars %></p>
        </div>
      </div>

      <div class="group has-text-justified">
        <%= @actor.description %>
      </div>
    </div>
  </div>
</div>