config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'films#index'

  resources :actors, only: %i[index show new create destroy]
  resources :films, only: %i[index show new create destroy] do
    scope module: :films do
      resources :reviews, only: %i[create]

    end
  end

  get '/films/:id'=>'films#show'
  get 'popularfilm' => 'popularfims#popularfilm'
  resources :reviews, only: :destroy
end

app/helpers/layouts_helper.rb
# frozen_string_literal: true

module LayoutsHelper
  def controller_javascript_pack_tag(**options)
    javascript_pack_tag(params[:controller].to_s, **options)
  rescue Webpacker::Manifest::MissingEntryError
    Rails.logger.debug { "No javascript pack for `#{params[:controller]}.js`" }

    nil
  end

  def controller_stylesheet_pack_tag(**options)
    stylesheet_pack_tag(params[:controller].to_s, **options)
  rescue Webpacker::Manifest::MissingEntryError
    Rails.logger.debug { "No stylesheet pack for `#{params[:controller]}.css`" }

    nil
  end

  def action_javascript_pack_tag(**options)
    javascript_pack_tag("#{params[:controller]}/#{current_action}", **options)
  rescue Webpacker::Manifest::MissingEntryError
    Rails.logger.debug { "No javascript pack for `#{params[:controller]}/#{current_action}.js`" }

    nil
  end

  def action_stylesheet_pack_tag(**options)
    stylesheet_pack_tag("#{params[:controller]}/#{current_action}", **options)
  rescue Webpacker::Manifest::MissingEntryError
    Rails.logger.debug { "No stylesheet pack for `#{params[:controller]}/#{current_action}.css`" }

    nil
  end

  def sidebar_link(label_or_path, path_or_controller, controller = nil, &block)
    klass = (controller || path_or_controller).to_s == params[:controller] ? 'is-active' : ''

    return link_to(label_or_path, path_or_controller, class: klass) if block.blank?

    link_to(label_or_path, class: klass, &block)
  end
end

app/views/layouts/_content.html.erb
<div class="section column is-four-fifth pt-0">
  <% if yield(:content_title).present? %>
    <div class="<%= ['hero', 'is-small', 'is-primary', yield(:content_title_class)].compact.join(' ') %>">
      <div class="hero-body level">
        <p class="title level-left mb-0">
          <%= yield(:content_title) %>
        </p>
        <div class="actions level-right">
          <%= yield(:content_title_actions) %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="<%= ['box', 'content', yield(:content_container_class)].reject(&:blank?).join(' ') %>">
    <%= yield %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <%= link_to t('company_name'), 'https://www.leobit.com', class: 'has-text-white has-text-weight-bold' %>
      ©
      <%= t('initial_year') %>
    </p>
  </div>
</footer>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar" class="sidebar column is-one-fifth p-0">
  <div class="menu">
    <p class="menu-label">General</p>
    <ul class="menu-list">
      <li>

        <%= sidebar_link actors_path, :actors do %>
        <span class="icon-text">
        <span class="icon">
       <i class="fa fa-users" aria-hidden="true"></i>
        </span>
        <span><%= 'Actors' %></span>
      </span>
        <% end %>


        <%= sidebar_link films_path, :films do %>
        <span class="icon-text">
        <span class="icon">
          <i class="fas fa-film"></i>
        </span>
        <span><%=t('films.nav') %></span>
      </span>
          <% end %>

        <%= sidebar_link popularfilm_path, :poularfilm do %>
        <span class="icon-text">
        <span class="icon">
          <i class="fa fa-fire" aria-hidden="true"></i>
        </span>
        <span><%= 'Most discussed films' %></span>
      </span>
        <% end %>
    </ul>
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield(:title).presence || page_title %></title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_pack_tag 'favicon.png' %>

    <%= stylesheet_packs_with_chunks_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- That's not a Rails magic, but manually written functionality in LayoutsHelper -->
    <%= controller_stylesheet_pack_tag media: 'all', data: { turbolinks_track: :reload } %>
    <%= action_stylesheet_pack_tag     media: 'all', data: { turbolinks_track: :reload } %>

    <%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- That's not a Rails magic, but manually written functionality in LayoutsHelper -->
    <%= controller_javascript_pack_tag data: { turbolinks_track: :reload } %>
    <%= action_javascript_pack_tag     data: { turbolinks_track: :reload } %>
  </head>

  <body>
    <div id="flash-container" data-flash="<%= flash.to_h.to_json %>"></div>

    <div id="body-wrapper" class="section columns">
      <%= render 'layouts/sidebar' %>
      <%= render 'layouts/content' %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= render 'layouts/footer' %>
  </body>
</html>